#!/bin/sh

rm -f src/bzip2/bzip2-*/*.o 
rm -f src/bzip2/bzip2-*/libbz2.a
rm -f src/bzip2/libH5Zbz2.so*

rm -f src/blosc/*.o
rm -f src/blosc/libblosc.a
rm -f src/blosc/libH5Zblosc.so
rm -f src/blosc/lib/blosc-*/*.o
rm -f src/blosc/lib/blosc-*/Makefile
rm -f src/blosc/lib/snappy-*/*.o
rm -f src/blosc/lib/lz4-*/*.o
rm -f src/blosc/lib/zstd-*/*.o 
rm -f src/blosc/lib/zstd-*/common/*.o 
rm -f src/blosc/lib/zstd-*/compress/*.o 
rm -f src/blosc/lib/zstd-*/decompress/*.o

rm -f src/lzf/lzf/*.o
rm -f src/lzf/lzf/liblzf.a
rm -f src/lzf/libH5Zlzf.so

rm -f src/rle/rle-0.0.1/*.o
rm -f src/rle/rle-0.0.1/librle.a
rm -f Turbo-Run-Length-Encoding/libtrle.a
rm -f Turbo-Run-Length-Encoding/*.o
rm -f rle8/*.o
rm -f rle8/librle8.a
rm -f src/rle/*.so

rm -f src/bitpack/*.so
rm -f src/bitpack/LittleIntPacker/*.o
rm -f src/bitpack/LittleIntPacker/liblip.a
rm -f src/bitpack/simdcomp/*.o
rm -f src/bitpack/simdcomp/libsimdcomp.a

rm -f src/Makevars