#!/bin/sh

rm -f src/bzip2/bzip2-*/*.o 
rm -f src/bzip2/bzip2-*/libbz2.a
rm -f src/bzip2/libH5Zbz2.so*

rm -f src/blosc/*.o
rm -f src/blosc/libblosc.a
rm -f src/blosc/libH5Zblosc.so
rm -f src/blosc/lib/blosc-*/*.o
rm -f src/blosc/lib/blosc-*/Makefile
rm -f src/blosc/lib/snappy-*/*.o
rm -f src/blosc/lib/lz4-*/*.o
rm -f src/blosc/lib/zstd-*/*.o 
rm -f src/blosc/lib/zstd-*/common/*.o 
rm -f src/blosc/lib/zstd-*/compress/*.o 
rm -f src/blosc/lib/zstd-*/decompress/*.o

rm -f src/lzf/lzf/*.o
rm -f src/lzf/lzf/liblzf.a
rm -f src/lzf/libH5Zlzf.so

# rm -f src/vbz/vbz/*.o
# rm -f src/vbz/vbz/v0/*.o
# rm -f src/vbz/vbz/v1/*.o
# rm -f src/vbz/third_party/streamvbyte/*.o
# rm -f src/vbz/third_party/streamvbyte/*.a
# rm -f src/vbz/libvbz.a
# rm -f src/vbz/libH5Zvbz.so

rm -f src/zstd/libzstd.a
rm -f src/zstd/common/*.o 
rm -f src/zstd/compress/*.o 
rm -f src/zstd/decompress/*.o
rm -f src/zstd/libH5Zzstd.so

rm -f src/Makevars