---
title: "Benchmarking filters"
author: "Mike Smith"
output: html_document
---

```{r}
library(dplyr)
library(rhdf5)
library(hdf5Filters)
library(ggplot2)
```

```{r, params}
chunk_dims = list(c(100, 100))
shuffle = c(TRUE, FALSE)
levels = 1:2
iterations <- 2L
workingdir <- tempdir()
```

```{r, dataload}
pbmc8k <- TENxPBMCData::TENxPBMCData("pbmc3k")
dat <- as.matrix(assay(pbmc8k))
```

```{r, define-functions}
write_test <- function(dat, filter = "DEFLATE", level = 6, shuffle = TRUE, chunk_dims = c(100, 100), h5File = NULL, rm = TRUE) {
    if(is.null(h5File))
        h5File <- tempfile(pattern = "write_", fileext = ".h5", tmpdir = tempdir())
    fid <- h5createFile(h5File)
    
    if(rm) { on.exit(file.remove(h5File), add = TRUE) }
    
    h5createDataset(file = h5File, 
                    dataset = "test",
                    dims = dim(dat),
                    chunk = chunk_dims,
                    filter = filter, 
                    level = level, 
                    shuffle = shuffle)

    write_time <- system.time(h5write(dat, file = h5File, name = "test"), gcFirst = FALSE)[3]
    
    return(tibble(filter, level, shuffle, 
                  chunk_dims = paste(chunk_dims, collapse = "x"),
                  write_time))
}

read_test <- function(h5File, filter = "DEFLATE", level = 6, shuffle = TRUE, chunk_dims = c(100, 100)) {
    
    read_time <- system.time(h5read(file = h5File, name = "test"), gcFirst = FALSE)[3]
    
    return(tibble(filter, level, shuffle, 
                  chunk_dims = paste(chunk_dims, collapse = "x"),
                  read_time))
}

filter_test <- function(dat, filter = "DEFLATE", level = 6, shuffle = TRUE, chunk_dims = c(100, 100), iterations = 3) {
    
    ## write test
    write_timings <- lapply(rep(filter, iterations), FUN = write_test, dat = dat, level = level, 
                            shuffle = shuffle, chunk_dims = chunk_dims, h5File = NULL, rm = TRUE) %>% 
        bind_rows()
    
    ## file size
    file_name <- tempfile(pattern = "read_", fileext = ".h5", tmpdir = tempdir())
    tmp <- write_test(dat = dat, level = level, shuffle = shuffle, 
               chunk_dims = chunk_dims, h5File = file_name, rm = FALSE)
    file_size <- file.size(file_name)
    
    ## read test
    read_timings <- lapply(rep(filter, iterations), FUN = read_test, level = level, 
                           shuffle = shuffle, chunk_dims = chunk_dims, h5File = file_name) %>% 
        bind_rows()
    
    file.remove(file_name)
    
    results <- write_timings %>% mutate(read_time = read_timings$read_time, file_size = file_size)
    results
}
```

```{r, uncompressed}
bm_uncmp <- filter_test(dat = dat, filter = "none", level = 0, iterations = iterations)
```


```{r, blosc_lz}
filters <- c("BLOSC_BLOSCLZ")
grid <- expand.grid(filter = filters, level = levels, shuffle = shuffle, 
                    chunk_dims = chunk_dims, stringsAsFactors = FALSE)
bm_blosclz <- mapply(FUN = filter_test, 
               filter = grid$filter, level = grid$level, shuffle = grid$shuffle, chunk_dims = grid$chunk_dims, 
               MoreArgs = list(dat = dat, iterations = iterations), 
               SIMPLIFY = FALSE) %>%
    bind_rows()
```

```{r, blosc_lz4}
filters <- c("BLOSC_LZ4", "BLOSC_LZ4HC")
grid <- expand.grid(filter = filters, level = levels, shuffle = shuffle, 
                    chunk_dims = chunk_dims, stringsAsFactors = FALSE)
bm_blosclz4 <- mapply(FUN = filter_test, 
               filter = grid$filter, level = grid$level, shuffle = grid$shuffle, chunk_dims = grid$chunk_dims, 
               MoreArgs = list(dat = dat, iterations = iterations), 
               SIMPLIFY = FALSE) %>%
    bind_rows()
```

```{r, blosc_snappy}
filters <- c("BLOSC_SNAPPY")
## snappy doesn't have compression levels
grid <- expand.grid(filter = filters, level = 1, shuffle = shuffle, 
                    chunk_dims = chunk_dims, stringsAsFactors = FALSE)
bm_snappy <- mapply(FUN = filter_test, 
               filter = grid$filter, level = grid$level, shuffle = grid$shuffle, chunk_dims = grid$chunk_dims, 
               MoreArgs = list(dat = dat, iterations = iterations), 
               SIMPLIFY = FALSE) %>%
    bind_rows()
```

```{r, deflate-bzip}
filters <- c("BLOSC_ZLIB", "GZIP", "BZIP2")
grid <- expand.grid(filter = filters, level = levels, shuffle = shuffle, 
                    chunk_dims = chunk_dims, stringsAsFactors = FALSE)
bm_deflate_bzip <- mapply(FUN = filter_test, 
               filter = grid$filter, level = grid$level, shuffle = grid$shuffle, chunk_dims = grid$chunk_dims, 
               MoreArgs = list(dat = dat, iterations = iterations), 
               SIMPLIFY = FALSE) %>%
    bind_rows()
```

```{r, blosc_zstd}
filters <- c("BLOSC_ZSTD")
## don't use levels over 8, it's super slow!
grid <- expand.grid(filter = filters, level = intersect(1:8, levels), shuffle = shuffle, 
                    chunk_dims = chunk_dims, stringsAsFactors = FALSE)
bm_deflate_zstd <- mapply(FUN = filter_test, 
               filter = grid$filter, level = grid$level, shuffle = grid$shuffle, chunk_dims = grid$chunk_dims, 
               MoreArgs = list(dat = dat, iterations = iterations), 
               SIMPLIFY = FALSE) %>%
    bind_rows()
```

```{r, combine}
bm_all <- bind_rows(bm_uncmp, bm_blosclz, bm_blosclz4,
                    bm_snappy, bm_deflate_bzip, bm_blosczstd)
saveRDS(bm_all, file = "bm_all.rds")
```

