---
title: "Benchmarking filters"
author: "Mike Smith"
output: html_document
---

```{r}
library(dplyr)
library(microbenchmark)
library(rhdf5)
library(stringr)
library(hdf5Filters)
library(ggplot2)
```

```{r, loadData}
pbmc8k <- TENxPBMCData::TENxPBMCData("pbmc3k")
dat <- as.matrix(assay(pbmc8k))
#levels <- c(1,2,3,4,5,6,7,8,9)
levels <- c(1,2,8)
iterations <- 2L
workingdir <- "/tmpdata/msmith/benchmark"
```

```{r, defineFunction}
run_test <- function(dat, filter, method, level, shuffle = TRUE, h5File = NULL, rm = TRUE) {
    if(is.null(h5File))
        h5File <- tempfile(pattern = "ex_save", fileext = ".h5", tmpdir = workingdir)
    fid <- H5Fcreate(h5File)
    on.exit(H5Fclose(fid))
    
    if(rm) { on.exit(file.remove(h5File), add = TRUE) }
    
    sid <- H5Screate_simple(dims = dim(dat), maxdims = dim(dat))
    on.exit( H5Sclose(sid), add = TRUE )
    tid <- rhdf5:::.setDataType(H5type = NULL, storage.mode = "integer")
    dcpl <- H5Pcreate("H5P_DATASET_CREATE"); 
    H5Pset_fill_time( dcpl, "H5D_FILL_TIME_ALLOC" )
    H5Pset_chunk( dcpl, c(100, 200))
    if(filter == "blosc") {
        hdf5Filters::H5Pset_blosc(dcpl, tid, method = method, level = level, shuffle = shuffle)
    } else if (filter == "gzip") {
        if(shuffle) { H5Pset_shuffle(dcpl) }
        rhdf5::H5Pset_deflate(dcpl, level = level)
    } else if (filter == "bzip2") {
        if(shuffle) { H5Pset_shuffle(dcpl) }
        hdf5Filters::H5Pset_bzip2(dcpl, level = level)
    } else if (filter == "szip") {
        if(shuffle) { H5Pset_shuffle(dcpl) }
        rhdf5:::H5Pset_szip(dcpl, options_mask = 1L, pixels_per_block = 32)
    } else if (filter == "none") {

    }
    did <- H5Dcreate(fid, paste0("test"), tid, sid, dcpl = dcpl)
    H5Dwrite(dat, h5dataset = did)
    H5Dclose(did)

}

```

```{r, uncompressed, cache = FALSE}
bm_uncmp <- microbenchmark::microbenchmark(
    run_test(dat, filter = "none"),
    run_test(dat, filter = "none", shuffle = FALSE),
    times = iterations, control = list(warmup = 1L)
)

uncmp_res <- as_tibble(bm_uncmp) %>%
    mutate(filter = "none", 
           level = "0", 
           shuffle = !stringr::str_detect(expr, "shuffle = FALSE"),
           time = time / 1e9) %>%
    select(filter, level, shuffle, time)
```

```{r, blosc-run, cache=FALSE}
bm_blosc <- list()
cores <- c(1,2,4,8,16)
for(i in cores) {
    Sys.setenv(BLOSC_NTHREADS=i)
    bm_blosc[[ paste(i) ]] <- microbenchmark::microbenchmark(
        run_test(dat, filter = "blosc", method = 1, level = 7),
        run_test(dat, filter = "blosc", method = 2, level = 7),
        run_test(dat, filter = "blosc", method = 3, level = 7),
        run_test(dat, filter = "blosc", method = 5, level = 7),
        run_test(dat, filter = "blosc", method = 6, level = 7),
        times = iterations, control = list(warmup = 1L))
}
```


