on:
  workflow_dispatch:
  push:
    branches:
      - devel
  pull_request:
    branches:
      - devel

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: '${{ matrix.config.os }} (R: ${{ matrix.config.r }}, System Libs: ${{ matrix.config.sys-libs }})'

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest,   r: 'devel',   sys-libs: 'false'}
        - { os: windows-11-arm,   r: 'devel',   sys-libs: 'false'}
        - { os: ubuntu-24.04,     r: 'devel',   sys-libs: 'false'}
        - { os: ubuntu-24.04-arm, r: 'release', sys-libs: 'false'}
        - { os: ubuntu-24.04,     r: 'devel',   sys-libs: 'true' }
        - { os: ubuntu-24.04,     r: 'release', sys-libs: 'true' }
        - { os: macos-26-intel,   r: 'devel',   sys-libs: 'false'}
        - { os: macos-latest,     r: 'devel',   sys-libs: 'false'}
    steps:
      - uses: actions/checkout@v7

      - name: Install system dependencies
        if: ${{ runner.os == 'linux' && matrix.config.sys-libs == 'true' }}
        run: sudo apt-get update && sudo apt-get install -y libblosc-dev libbz2-dev libzstd-dev liblzf-dev

      - name: Remove system dependencies
        if: ${{ runner.os == 'linux' && matrix.config.sys-libs == 'false' }}
        run: sudo apt-get update && sudo apt-get remove -y libblosc-dev libbz2-dev libzstd-dev liblzf-dev
        
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - name: Install openssl
        if: runner.os == 'macOS'
        run: |
          sudo R -e 'source("https://mac.R-project.org/bin/install.R")' -e 'install.libs("openssl")'

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'

