on:
  push:
    branches:
      - master
      - arch-checks
  pull_request:
    branches:
      - master

name: ARM64 R-CMD-check 

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
          
      - name: Make library
        run: mkdir -p /home/runner/work/_temp/_github_home/r_library
          
      - name: Install R packages
        uses: docker://arm64v8/r-base:latest
        with:
          args: >
            Rscript -e ".libPaths('/github/home/r_library')" -e "install.packages(c('BiocManager', 'remotes'))"
            
      - name: List R packages
        uses: docker://arm64v8/r-base:latest
        with:
          args: >
            Rscript -e ".libPaths('/github/home/r_library')" -e "as.vector(installed.packages()[,'Package'])"

            
